spring:
  application:
    name: father-backend
  datasource:
    url: jdbc:mysql://localhost:3306/father
    username: root
    password: 123456
server:
  port: 8081
  servlet:
    context-path: /api
